### ISSUE TITLE
Can´t send Direkt Messages

### ISSUE THREAD

**Issue by JPRuehmann** [mikutter/mikutter#9]
Hello
I can´t send Direct Messages from within Mikutter, except to me.
If I open the Profile of a Twitter user go to the Direct Message Tab, enter a Message and push send it won´t get send but a new message bar is created and the first keeps displayed the only way to go back to normal is to close Mikutter and start it anew.

I am using Mikutter 3.5.9-7-g6a94e69 in Kubuntu 16.04 LTS
Thanks,

**Comment by JPRuehmann** [comment]
Will there a version out in the future with which I can send Direct Messages?

The Version comming out tonight 3.5.12 still can not do it.

Thanks,

**Comment by JPRuehmann** [comment]
Could it be possible that Direct messages could only be send to followers?
If that is so There should be an error "The Recipient is not following you." or so instead of Quietly not sending and hanging the Editor. Or to send it Quietly as normal message such as for example Twidere seems to do.

Thanks,

**Comment by toshia** [comment]
I think two reason.

1. Invalid permission for Twitter access token
   Twitter has 3 access level:
   - read
   - read&write
   - read&write&DM

   If your first mikutter is old token, you can't send/receive DM.
   We have workarounds. try:
   1. open Preference
      ![deepinscreenshot_select-area_20171116221945](https://user-images.githubusercontent.com/586906/32893304-4a8a6720-cb1c-11e7-9501-81a55f26653f.png)
   1. Choose your account.
   1. Click "Delete" in right button. (It will remove register in mikutter.)
   1. Click "Add".
   1. Register your account again.

   It will modify Twitter access token. retry send DMs.

2. Third-party plugin (Environment)
   mikutter is extensible. But It causes strange side effect in rarely.
   If you can't fix this issue in above, the problem is rarely and difficulty.

**Comment by JPRuehmann** [comment]
I´ve tried both but it won´t help.
Hope this won´t get forgotten.
Have you gotten DirectMessages from me in the past?
I´ve send you one by Twidere but this shows only as normal message.
Could you follow me to try if that is the Problem?
Thanks,

**Comment by toshia** [comment]
I don't follow you and don't accept direct message out of followee by twitter settings. It will deny send direct message.
Can you send another account that mutually following or yourself?

> I´ve send you one by Twidere but this shows only as normal message.

I don't know Twidere. but it looks wrong behavior. You should use official client or web for inspect this issue.

**Comment by JPRuehmann** [comment]
Hello,

that explains much.
Than the behaviour is quite normal.
nonetheless it would be better if there would be a message that tje message could not be send, if it is possible with an explanation such as you cannnot send a Direct Message to this Person or so.

With the following me was only a Question for testing purposes nothing more, sorry if I annoyed you.
Twidere is an openSource Twitter Client for Android.
With the behaviour of that Programm in that sense you are perfectly right I think.

The official Client is such an ugly and hard to use part of Software that I don´t want to use it.
Thanks,
